Import numpy as np and print the version number.

In [1]:
import numpy as np
np.__version__

'1.16.2'

Create a 1D array of numbers from 0 to 9

In [5]:
a=np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 3×3 numpy array of all True’s

In [7]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [29]:
sampleArray=np.random.randint(1,100,10)
oddArray=sampleArray[sampleArray%2==1]
oddArray

array([81, 75, 41, 53])

Replace all odd numbers in arr with -1

In [31]:
np.where(sampleArray%2==1,-1,sampleArray)
# np.where(oddArray%2==1,-1,oddArray)

array([-1,  4,  4, -1, 94, 38, -1, 44, 96, -1])

Convert a 1D array to a 2D array with 2 rows

In [33]:
sampleArray.reshape(2,5)

array([[81,  4,  4, 75, 94],
       [38, 41, 44, 96, 53]])

Stack arrays a and b vertically
> `a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)`

In [40]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)
np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally.

In [41]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Get the positions where elements of a and b match<br>

Input:<br>

> `a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])`

In [62]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
i=0
while(i<len(a)):
    if a[i]==b[i]:
        print(i)
    i-=-1

1
3
5
7


Get all items between 5 and 10 from a.<br>

Input:<br>

>`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [73]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<10)]

array([6, 9])

<pre>Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])</pre>

In [75]:
def maxx(x, y):
    if x >= y:
        return x
    else:
        return y
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
v=np.vectorize(maxx)
v(a,b)

array([6, 7, 9, 8, 9, 7, 5])

<pre>swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr</pre

In [102]:
arr = np.arange(9).reshape(3,3)
arr[:,[0,2,1]]


array([[0, 2, 1],
       [3, 5, 4],
       [6, 8, 7]])

<pre>How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)
arr</pre

In [91]:
arr = np.arange(9).reshape(3,3)
arr[[2,1,0]]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [93]:
#arr[[1,2],[0,2]]
arr[:,[2,1,0]]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

<pre>Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr</pre>

Write a NumPy program to generate five random numbers from the normal distribution

Write a NumPy program to generate six random integers between 10 and 30

In [104]:
randArray=np.random.randint(10,30,6)
randArray

array([13, 28, 18, 12, 12, 17])

Write a NumPy program to create a 3x3x3 array with random values

In [ ]:
a=np.random.random()

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

 Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

Read an JPEG image into a numpy array, return the size and shap of that image
